services:
  - type: web
    name: girlfriend-ui-project
    env: node
    installCommand: npm install
    buildCommand: npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: NODE_ENV
        value: production
